[tool.ruff]
line-length = 88
# Either replace ignore list:
# ignore = ["F401"]
# Or *extend* the default ignores (safer)
extend-ignore = ["F401"]

select = ["D"]

ignore = [
    "D100",  # module
    "D104",  # package
    "D105",  # magic methods
]
